# Generated by Django 6.0.2 on 2026-04-25 02:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='家庭名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('invite_code', models.CharField(blank=True, max_length=8, unique=True, verbose_name='邀请码')),
            ],
            options={
                'verbose_name': '家庭',
                'verbose_name_plural': '家庭管理',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='单词')),
                ('pronunciation', models.CharField(blank=True, max_length=100, verbose_name='音标')),
                ('definition', models.TextField(verbose_name='中文释义')),
                ('example', models.TextField(blank=True, verbose_name='例句')),
                ('example_translation', models.TextField(blank=True, verbose_name='例句翻译')),
                ('unit', models.CharField(default='Unit 1', max_length=50, verbose_name='单元')),
                ('textbook', models.CharField(default='课本词汇', max_length=50, verbose_name='教材')),
                ('is_core', models.BooleanField(default=True, verbose_name='课标核心词')),
                ('difficulty', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3, verbose_name='难度等级')),
                ('category', models.CharField(blank=True, help_text='例如：CET-4、雅思、课本', max_length=50, verbose_name='分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='任务标题')),
                ('due_date', models.DateField(verbose_name='截止日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='进行中')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL, verbose_name='分配给孩子')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL, verbose_name='创建家长')),
                ('words', models.ManyToManyField(to='words.word', verbose_name='单词列表')),
            ],
            options={
                'verbose_name': '学习任务',
                'verbose_name_plural': '学习任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=1, verbose_name='当前关卡')),
                ('total_score', models.IntegerField(default=0, verbose_name='总积分')),
                ('combo', models.IntegerField(default=0, verbose_name='当前连击')),
                ('max_combo', models.IntegerField(default=0, verbose_name='最高连击')),
                ('lives', models.IntegerField(default=3, verbose_name='剩余生命')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PDFWordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('words_extracted', models.IntegerField(default=0, verbose_name='提取单词数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.family', verbose_name='所属家庭')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': 'PDF导入记录',
                'verbose_name_plural': 'PDF导入记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('parent', '家长'), ('child', '孩子')], default='child', max_length=10, verbose_name='角色')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='昵称/小名')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='年级')),
                ('avatar', models.CharField(blank=True, default='👶', max_length=10, verbose_name='头像emoji')),
                ('daily_goal', models.IntegerField(default=10, verbose_name='每日目标')),
                ('current_streak', models.IntegerField(default=0, verbose_name='连续天数')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='words.family', verbose_name='所属家庭')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('words_learned', models.IntegerField(default=0)),
                ('words_reviewed', models.IntegerField(default=0)),
                ('homework_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_words', models.IntegerField(default=0, verbose_name='完成数量')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.familytask')),
            ],
            options={
                'unique_together': {('task',)},
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', '新学'), ('familiar', '熟悉'), ('mastered', '掌握')], default='new', max_length=20, verbose_name='状态')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下次复习')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正确次数')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repetitions', models.IntegerField(default=0, verbose_name='连续成功次数')),
                ('interval', models.IntegerField(default=1, verbose_name='间隔天数')),
                ('ease_factor', models.FloatField(default=2.5, verbose_name='简易度系数')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='总复习次数')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True, verbose_name='上次复习')),
                ('is_learned', models.BooleanField(default=False, verbose_name='是否已学')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
