# Generated by Django 6.0.2 on 2026-03-28 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_registrationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=1, verbose_name='当前关卡')),
                ('total_score', models.IntegerField(default=0, verbose_name='总积分')),
                ('combo', models.IntegerField(default=0, verbose_name='当前连击')),
                ('max_combo', models.IntegerField(default=0, verbose_name='最高连击')),
                ('lives', models.IntegerField(default=3, verbose_name='剩余生命')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
